"""
Pine Script Cross-Compiler

Provides bidirectional translation between Python (SLATE) and Pine Script v5.
Pine Script uses 0-based array indexing (same as Python), so no index translation needed.

Pine Script v5 Facts:
- TradingView's proprietary scripting language
- 0-based array indexing (same as Python)
- 100+ built-in indicators and functions
- Strongly typed with type inference
- Paper trading only - NO LIVE TRADING
"""

import re
import logging
from typing import Dict, List, Optional, Any
from dataclasses import dataclass

logger = logging.getLogger(__name__)


class PineScriptCrossCompiler:
    """
    Bidirectional Python ↔ Pine Script v5 compiler.

    Note: Pine Script uses 0-based indexing (like Python), so no index translation needed.
    """

    def __init__(self):
        self.warnings: List[str] = []

    def python_to_pine_script(self, python_code: str) -> str:
        """Convert Python (SLATE) code to Pine Script v5."""
        self.warnings = []

        lines = python_code.split('\n')
        pine_lines = []

        # Add Pine Script header
        pine_lines.append("// Generated by SLATE Pine Script Cross-Compiler")
        pine_lines.append("// Mode: PAPER_TRADING_ONLY")
        pine_lines.append("//@version=5")
        pine_lines.append("strategy('SLATE Strategy', overlay=true, process_orders_on_close=true)")
        pine_lines.append("")

        for line in lines:
            pine_line = self._convert_python_line_to_pine(line)
            if pine_line:
                pine_lines.append(pine_line)

        return '\n'.join(pine_lines)

    def pine_script_to_python(self, pine_code: str) -> str:
        """Convert Pine Script v5 to Python (SLATE)."""
        self.warnings = []

        lines = pine_code.split('\n')
        python_lines = []

        # Add Python header
        python_lines.append("# Generated by SLATE Pine Script Cross-Compiler")
        python_lines.append("# Mode: PAPER_TRADING_ONLY")
        python_lines.append("")

        for line in lines:
            python_line = self._convert_pine_line_to_python(line)
            if python_line:
                python_lines.append(python_line)

        return '\n'.join(python_lines)

    def validate_pine_script(self, code: str) -> Dict[str, Any]:
        """Validate Pine Script v5 code syntax."""
        errors = []
        warnings = []

        # Check for Pine Script version directive
        if '@version' not in code:
            errors.append("Missing //@version=5 directive")

        # Check for strategy or study declaration
        if 'strategy(' not in code and 'study(' not in code:
            errors.append("Missing strategy() or study() declaration")

        return {
            'valid': len(errors) == 0,
            'errors': errors,
            'warnings': warnings
        }

    def _convert_python_line_to_pine(self, line: str) -> Optional[str]:
        """Convert Python line to Pine Script."""
        # Skip comments
        if line.strip().startswith('#'):
            return '// ' + line.strip()[1:]

        # Skip empty lines
        if not line.strip():
            return None

        # Convert Python operators
        line = re.sub(r'\band\b', ' and ', line)
        line = re.sub(r'\bor\b', ' or ', line)
        line = re.sub(r'\bnot\b', ' not ', line)
        line = re.sub(r'\bNone\b', 'na', line)
        line = re.sub(r'\bTrue\b', 'true', line)
        line = re.sub(r'\bFalse\b', 'false', line)

        # Convert Python functions to Pine Script
        line = re.sub(r'\bget_close_prices\s*\(\)', 'close', line)
        line = re.sub(r'\bget_high_prices\s*\(\)', 'high', line)
        line = re.sub(r'\bget_low_prices\s*\(\)', 'low', line)
        line = re.sub(r'\bget_open_prices\s*\(\)', 'open', line)

        # Convert ta. functions
        line = re.sub(r'\brsi\s*\(', 'ta.rsi(', line)
        line = re.sub(r'\bsma\s*\(', 'ta.sma(', line)
        line = re.sub(r'\bema\s*\(', 'ta.ema(', line)
        line = re.sub(r'\bmacd\s*\(', 'ta.macd(', line)

        # Convert trading functions
        line = re.sub(r'\bgo_long\s*\(', 'strategy.entry("Long", strategy.long)', line)
        line = re.sub(r'\bgo_short\s*\(', 'strategy.entry("Short", strategy.short)', line)
        line = re.sub(r'\bexit_position\s*\(', 'strategy.close_all()', line)

        # Convert Python keywords to Pine Script
        line = re.sub(r':\s*$', '', line)  # Remove colon
        line = re.sub(r'\belif\b', 'else if', line)
        line = re.sub(r'\bpass\b', '// pass', line)

        # Convert def to Pine Script function syntax
        if line.strip().startswith('def '):
            line = re.sub(r'def\s+(\w+)\s*\(([^)]*)\)\s*->\s*(\w+):', r'\2 => \3', line)
            line = re.sub(r'def\s+(\w+)\s*\(([^)]*)\):', r'\1(\2) =>', line)

        return line

    def _convert_pine_line_to_python(self, line: str) -> Optional[str]:
        """Convert Pine Script line to Python."""
        # Skip comments
        if line.strip().startswith('//'):
            return '# ' + line.strip()[2:]

        # Skip empty lines and directives
        if not line.strip() or line.strip().startswith('//@'):
            return None

        # Convert Pine Script operators to Python
        line = re.sub(r'\bna\b', 'None', line)
        line = re.sub(r'\btrue\b', 'True', line)
        line = re.sub(r'\bfalse\b', 'False', line)

        # Convert ta. functions to Python
        line = re.sub(r'\bta\.rsi\s*\(', 'rsi(', line)
        line = re.sub(r'\bta\.sma\s*\(', 'sma(', line)
        line = re.sub(r'\bta\.ema\s*\(', 'ema(', line)
        line = re.sub(r'\bta\.macd\s*\(', 'macd(', line)

        # Convert built-in price variables
        line = re.sub(r'\bclose\b', 'get_close_prices()[-1]', line)
        line = re.sub(r'\bhigh\b', 'get_high_prices()[-1]', line)
        line = re.sub(r'\blow\b', 'get_low_prices()[-1]', line)
        line = re.sub(r'\bopen\b', 'get_open_prices()[-1]', line)

        # Convert strategy functions
        if 'strategy.entry' in line and 'strategy.long' in line:
            line = 'go_long()'
        elif 'strategy.entry' in line and 'strategy.short' in line:
            line = 'go_short()'
        elif 'strategy.close_all' in line:
            line = 'exit_position()'

        # Convert Pine Script keywords to Python
        line = re.sub(r'\belse if\b', 'elif', line)
        line = re.sub(r'=\s*$', ':', line)  # Add colon for blocks
        line = re.sub(r'=>', ':', line)  # Arrow function to def

        return line
